version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=claim-FsdoFxHP9uay1dtvo2en
    volumes:
      # - /path/to/library:/config
      - /media/marc/MediaShare/Shows:/tv
      - /media/marc/MediaShare/Movies:/movies
    restart: unless-stopped